### PR TITLE
Added Generate Stage OpenAI helper and fixes to `generateTrip` and removed UUID references

### LINKED ISSUE #148: Make id consistent in database

### LINKED ISSUE #156: Remove UUID usage in FE

### PR DESCRIPTION
**Pull request by L0Lmaker**

### CODE REVIEW

**Comment by L0Lmaker** [comment]
Didnt see any major UUID usages that impacted render

**Review by NLmeng — APPROVED** [review]
tested it out, works fine

File: server/models/StageModel.js [hunk 1]
```diff
@@ -1,12 +1,8 @@
...
 
 const stageSchema = new mongoose.Schema({
-  _id: {
-    type: String,
-    required: true,
-  },
   tripId: {
-    type: String,
+    type: mongoose.Schema.Types.ObjectId,
     required: true,
```
Comment (NLmeng) [inline server/models/StageModel.js:6]: i dont think we will necessarily need this for our app, but it's nice to add this (allow usage of .populate(), and the collection actually knows about the relationship):
```
  tripId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Trip',
    required: true,
  },
```
