### PR TITLE
fix map marker using emoji

### LINKED ISSUE #139: Fix map's pin

### PR DESCRIPTION
**Pull request by NLmeng**
closes #139

### CODE REVIEW

File: client/src/components/MapElement/MapElement.js [hunk 1]
```diff
@@ -42,14 +42,9 @@ export function MapElement({ className }) {
...
-      latitude,
-      imgSrc = 'https://pngimg.com/d/google_maps_pin_PNG56.png',
-      altText = 'Marker Icon',
-    ) => {
+    (longitude, latitude, emoji, label) => {
       const markerElement = document.createElement('div')
-      markerElement.innerHTML = `<img src='${imgSrc}' alt='${altText}' style='width: 40px; height: 40px;'/>`
+      markerElement.innerHTML = `<p id=${label} style='width: 40px; height: 40px; font-size: 40px;'> ${emoji} <p>`
       const marker = new mapboxgl.Marker(markerElement)
         .setLngLat([longitude, latitude])
```
Comment (Graywing13) [inline client/src/components/MapElement/MapElement.js:52]: suggestion: do we want to use the label for smth other than id? e.g. 

```
.setPopup(new mapboxgl.Popup().setHTML("<p>{label}</p>")) 
```

**Review by Graywing13 — APPROVED** [review]
lgtm minor suggestion to consider
